#!/usr/bin/env bash
# Palindrome - Identifies all palindromic words within a text file.

main() {
    textfile=$1 
	
    cat $textfile \
		| to_lower_case \
		| remove_hyphenated_words \
        | remove_punctuation \
		| remove_numerals \
		| remove_short_words \
		| remove_single_letter_words \
		| match_first_and_last_letter \
		| find_palindromes \
		| count_unique_words
}		

to_lower_case() {
    tr '[:upper:]' '[:lower:]'
}

remove_hyphenated_words() {
	sed 's/\b\w*[-]\w+//g'
}

remove_punctuation() {
	tr -d '[:punct:]'
}

remove_numerals() {
	sed 's/\w*[0-9]\w*//g'
}

remove_short_words() {
	sed -r 's/\b[a-z]{1,2}\b//g'
}

remove_single_letter_words() {
	sed -r 's/\b([a-z])\1*\b//g'
}

match_first_and_last_letter() {
	grep -P -o '\b([a-z])[a-z]*\1\b' 
}

find_palindromes() {
	while read word;
	do
		reversed=$(echo $word | rev)
		
		if [ $reversed = $word ]
		  then
			echo $word
		fi
        
	done
}

count_unique_words() {
	sort | uniq -c | sort -nr 
}

main $1